[compile]
unroll-puzzle = "clsp/unroll/unroll_puzzle.clsp"
unroll-meta-puzzle = "clsp/unroll/unroll_meta_puzzle.clsp"
debug-game = "clsp/test/debug_game.clsp"
calpoker-generate = "clsp/games/calpoker/calpoker_include.clsp"
onchain-referee = "clsp/referee/onchain/referee.clsp"
handcalc-micro = "clsp/test/test_handcalc_micro.clsp"
make-cards = "clsp/test/test_make_cards.clsp"
deep-compare = "clsp/test/deep_compare.clsp"
test-mergein = "clsp/test/test_mergein.clsp"
